name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Git 리포지토리 체크아웃 진행 ..
      - name: 1. Git 리포지토리 체크아웃 진행 ..
        uses: actions/checkout@v2

      # 2. Docker 로그인을 위한 환경 변수 설정 중 ..
      - name: 2. Docker 로그인을 위한 환경 변수 설정 중 ..
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3. Docker 이미지 빌드 중 ..
      - name: 3. Docker 이미지 빌드 중 ..
        run: docker build -t yeonghuns/kosa-denkins-bot:latest .

      # 4. Docker 이미지 푸시 중 ..
      - name: 4. Docker 이미지 푸시 중 ..
        run: docker push yeonghuns/kosa-denkins-bot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 5. SSH로 EC2에 접속하여 Docker 이미지 Pull 및 실행 ..
      - name: 5. SSH로 EC2에 접속하여 Docker 이미지 Pull 및 실행 ..
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          timeout: 60s
          script: |
            cd .docker/
            docker pull yeonghuns/kosa-denkins-bot:latest
            docker stop discord-bot || true
            docker rm discord-bot || true
            docker run -d --name discord-bot --env-file .env yeonghuns/kosa-denkins-bot:latest